version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: scratch_role
      POSTGRES_DB: crowdfund
    ports:
      - 5432:5432
